name: highwayheartbeats
description: "Highway Heartbeats: The rhythm of the road, the beat of friendship."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  share_plus: ^9.0.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/kavinsky.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/ryan.gif